### ISSUE TITLE
[62.3] Create open Textbooks "Guides and Toolkits" component

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#94] opened 2019-02-22 20:56 UTC
Page 8 in open.Bccampus.ca template markup (located in two places on this page.)

**Comment by alex-418** [comment] 2019-02-22 22:33
![screen shot 2019-02-22 at 2 31 23 pm](https://user-images.githubusercontent.com/17072191/53275151-d5c24980-36ae-11e9-9736-ef5ba0430a44.png)

**Comment by alex-418** [comment] 2019-02-22 22:35
@ehbeattie to provide content (guides and links)

**Comment by bdolor** [comment] 2019-03-12 17:43
duplicate of https://github.com/BCcampus/open-sage/issues/114

**Closed as completed by bdolor** 2019-03-12 17:43 UTC
Labels: medium-3
