### ISSUE TITLE
[Footer] Subscribe page template 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/open-sage#41] opened 2019-01-28 18:08 UTC
Create page template so that the subscribe page can be assigned this template, it should include the campaign monitor code that generates the form.

**Comment by alex-418** [comment] 2019-02-06 00:50
Covered in #40

**Comment by ehbeattie** [comment] 2019-02-07 20:56
Ok.

**Comment by bdolor** [comment] 2019-02-07 21:28
@ehbeattie the form that's embedded doesn't look like the type of form you would want on prod. Can you please confirm that the subscription form on this page is the correct campaign monitor form? 

https://helga.bccampus.ca/wp/opentextbooks/subscribe/

**Comment by ehbeattie** [comment] 2019-02-07 21:31
@bdolor We would like the same form as we have on BCcampus: https://bccampus.ca/subscribe/?subscribe=

**Comment by bdolor** [comment] 2019-02-07 22:16
moving this back to doing...was the id for the form given in https://github.com/BCcampus/open-sage/issues/40#issuecomment-460833885 the correct one? 

When this goes through validation process, we should ensure it is the correct form and (if possible) ensure that the form works as intended.

**Comment by ehbeattie** [comment] 2019-02-07 22:21
Hi @bdolor 

I gave @alex-418 access to the backend of Campaign Monitor and the only link that I'm aware of for the id, but honestly, I'm not sure what part is needed to make it look like the BCcampus subscription form.

**Comment by alex-418** [comment] 2019-02-07 23:29
@ehbeattie I created a custom form with the same elements on the bccampus.ca website for this campaign monitor list and it should now be on helga. (via https://github.com/BCcampus/open-sage/pull/58)

**Closed as completed** 2019-02-13 23:00 UTC
Labels: small-1
